config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'groups#index'
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
    end
  end
  
 
  namespace :account do
    resources :groups
    resources :posts
  end
  
  #不用命名空间，下面这种自由的配置方式在仅需查看的场景下可以，如果还需要有编辑删除等操作，路由定义就比较麻烦
  # get 'groups/join/my', to: 'groups#showMyJoinedGroups'
  # get 'posts/my', to: 'posts#showMyPosts'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :title,presence: true
  belongs_to :user
  has_many :posts
  has_many :group_relationships
  #group和加入的成员(members)是多对多关系，通过中间表group_relationships
  has_many :members,through: :group_relationships,source: :user
  
end

app/models/group_relationship.rb
class GroupRelationship < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content,presence: true
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #用户创建的group（和加入的group还不一样）
  has_many :groups
  has_many :posts
  has_many :group_relationships
  #user和joined_groups(加入的版块)多对多关系，通过中间表group_relationships
  has_many :joined_groups,:through => :group_relationships,:source => :group
  
  def is_member_of?(group)
    joined_groups.include?(group)
  end
  def join(group)
    joined_groups << group
  end
  def quit(group)
    joined_groups.delete(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @myJoinedGoups=current_user.joined_groups
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    #这个实体变量也可以不在controller中定义，也可以在view中直接访问Post.xxx。但这个action必须定义，否则路由匹配不到。
    @myPosts=Post.where(user_id:current_user.id)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  #必须登录用户才能进行以下操作(action)
  before_action :authenticate_user!, only:[:new,:create,:edit,:update,:destroy,:join,:quit]
  
  def index
    @groups=Group.all
  end
  
  def show
    @group=Group.find(params[:id])
    #@group.posts：拥有的所有post对象，根据has_many
    @posts=@group.posts.order("created_at DESC").paginate(:page => params[:page],:per_page => 5)
  end
  
  #new对应表单。填完以后可以送出 (使用 GET )
  def new
    @group=Group.new
  end
  #new 送出来的表单到 create 这个 action，新增一笔数据 ( 使用 POST )
  def create
    @group=Group.new(group_params)
    #group model里定义了belongs_to :user，所以@group.user可以对应到user对象
    #这里把@group所属的user对象指定为 current_user对象。然后他们会自动做关联 也就是@group.user_id会自动变成current_user.id。
    @group.user=current_user
    if @group.save
      #创建版块的人自动加入该版块
      current_user.join(@group)
      redirect_to groups_path
    else
      render "new"
    end
  end
  
  #edit对应表单。填完以后可以送出 (使用 GET )
  def edit
    @group=Group.find(params[:id])
    #直接通过网址访问edit表单页时，也是该action响应；所以要判断如果当前用户不是该group的创建者，重定向到首页，并提示信息（edit按钮在html）
    if current_user!=@group.user
      redirect_to root_path
      flash[:alert]="你没有权限"
    end 
  end
  #edit 送出来的表单可以到 update 这个 action，更新该笔数据 (使用 PUT )
  def update
    @group=Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path,notice:"修改成功"
    else
      render "edit"
    end
  end
  
  def destroy
    @group=Group.find(params[:id])
    @group.destroy
    flash[:alert]="版块删除成功"
    redirect_to groups_path
  end
  
  #定义加入版块和退出版块的action，调用model层方法
  #该action在页面点击join按钮时触发
  def join
    @group=Group.find(params[:id])
    if !current_user.is_member_of?(@group)
      current_user.join(@group)
      flash[:notice]="加入版块成功"
    else
      flash[:warning]="你已是该版块成员"
    end
    redirect_to group_path(@group)
  end
  
  def quit
    @group=Group.find(params[:id])
    if current_user.is_member_of?(@group)
      current_user.quit(@group)
      flash[:notice]="退出版块成功"
    else
      flash[:warning]="你还不是该版块成员，无需退出"
    end
    redirect_to group_path(@group)
  end
  
  

  
  
  private
  def group_params
    params.require(:group).permit(:title,:description)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  
  def index
    @group=Group.find(params[:group_id])
    @posts=Post.all
  end
  
  def new
    @group=Group.find(params[:group_id])
    @post=Post.new
  end
  def create
    @group=Group.find(params[:group_id])
    @post=Post.new(post_params)
    @post.group=@group
    @post.user=current_user
    if @post.save
      redirect_to group_path(@group),notice:"发布主题成功"
    else
      render :new
    end
  end
  
  #需要获取的参数（对应实体变量定义），要根据rake routes中该action对应的url中的参数
  def edit
    #url中有group_id参数
    @group=Group.find(params[:group_id])
    @post=Post.find(params[:id])
  end
  def update
    @group=Group.find(params[:group_id])
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to account_posts_path
    else
      render "edit"
    end
  end
  
  def destroy
    @group=Group.find(params[:group_id])
    @post=Post.find(params[:id])
    @post.destroy
    flash[:alert]="删除成功"
    redirect_to account_posts_path
    
  end
  
  

  private
  def post_params
    params.require(:post).permit(:content)
  end
  
end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning" 
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Rails103</a>
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav navbar-right mr-auto">
      <li class="nav-item active">
		               <% if !current_user %>
		                <li><%= link_to("注册", new_user_registration_path) %> </li>
		                <li><%= link_to("登录", new_user_session_path) %></li>
		               <% else %>
		                <li class="dropdown">
		                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		                       Hi!, <%= current_user.email %>
		                       <b class="caret"></b>
		                   </a>
		                   <ul class="dropdown-menu">
		                       <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
						   <li> <%= link_to("我发布的主题", account_posts_path) %> </li>
						   <li> <%= link_to("我加入的版块", account_groups_path) %> </li>
		                   </ul>
		                 </li>
		              <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/groups/_form.html.erb
  
  <%= form_for @group do |f| %>
  
  <% if @group.errors.any? %>
  <ul>
    <% @group.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
 <%end  %>
  </ul> 
  <%end %>
  
  <div class="form-group">
  
    <div class="form-group string optional">
    标题
    <%= f.text_field :title,:class => "string optional form-control"%>
    </div>
    
    <br>
    描述
    <br>
    <%= f.text_area :description,:class =>"string optional form-control " %>
    <br>
    <%= f.submit "提交",:class => "btn btn-primary" %>
	
 </div>
   <%end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑版块</h2>
  <hr>
	
  <%= render "form" %>
  <%= link_to("取消",groups_path,class:"btn btn-default") %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
	<h2>Rails103</h2>
	<div id="new">
		<%= link_to("新建版块",new_group_path,class:"btn btn-primary") %>
	</div>
  <table class="table table-hover">
	<thead>
		<tr>
		  <td>版块标题</td>
		  <td>版块描述</td>
		  <td>创建人</td>
		  <td>操作</td>
		</tr>
	</thead>
	<tbody>
		<% @groups.each do |g| %>
		<tr>
		  <td><%= link_to(g.title,group_path(g)) %></td>	
		  <td><%= g.description %></td>
		   <!-- 下面的g.user指当前版块所属的user对象(group model中声明了belongs_to user了) -->
		  <td><%= g.user.email %></td>
		  <% if current_user && g.user==current_user %>	
		  <td><%= link_to("编辑",edit_group_path(g)) %></td>	
		  <td><%= link_to("删除",group_path(g),method: :delete,data:{confirm:"确定删除？"}) %></td>	
		  <%end %>
		</tr>
		<%end  %>
	</tbody>	
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增版块</h2>
  <hr>
	
  <%= render "form" %>
  
  <%= link_to("取消",groups_path,class:"btn btn-default") %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <h2>版块详情</h2>
  <hr>
  
  <div class="group">
    <h3><%= @group.title %></h3>
    <p><%= @group.description %></p>
  </div>
  
  <div class="post">
  	<table class="table table-hover">
  		<thead>
  			<tr>
  				<th>主题内容</th>
				<th>发布人</th>
				<th>发布时间</th>
  			</tr>
  		</thead>
  		<tbody>
			<%= @posts.each do |p| %>
  			<tr>
  				<td><%= p.content %></td>
				<td><%= p.user.email %></td>
				<td><%= p.created_at %></td>
  			</tr>
			<%end %>
  		</tbody>
</table>
<div id="name">
	<%= will_paginate @posts %>
</div>
  </div>
  
  <div class="">
    <% if current_user.is_member_of?(@group) %>
      <label class="label label-success">版块成员</label>
	 <%= link_to("退出版块",quit_group_path(@group),method: :post,class:"btn btn-default") %>
      <%= link_to("发布主题",new_group_post_path(@group),class:"btn btn-primary") %>
	
    <%else %>
      <label class="label label-warning">非版块成员</label>
	 <%= link_to("加入版块",join_group_path(@group),method: :post,class:"btn btn-default") %>
    <%end %>
    
    <% if current_user && current_user==@group.user %>
      <%= link_to("编辑版块",edit_group_path(@group),class:"btn btn-default") %>
    <%end %>
    <%= link_to("返回",groups_path,class:"btn btn-default") %>
  </div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails103</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar"%>
	 <%= render "common/flashes"%>
	 <%= yield %>
    </div>
   
  </body>
</html>

app/views/posts/edit.html.erb
     <h2>编辑主题</h2>
	<%= form_for [@group,@post] do |f| %>
	主题内容
	<br>
	<div class="form-group string optional">
	  <%= f.text_area :content,:class =>"string optional form-control"  %>
	</div>
	  <%= f.submit "提交",:class =>"btn btn-primary" %>
	  <%= link_to("取消",account_posts_path,class:"btn btn-default") %>
    
	
	<%end %>
	

app/views/posts/new.html.erb
     <h2>发布主题</h2>
	<%= form_for [@group,@post] do |f| %>
	主题内容
	<br>
	<div class="form-group string optional">
	  <%= f.text_area :content,:class =>"string optional form-control"  %>
	</div>
	  <%= f.submit "提交",:class =>"btn btn-primary" %>
	  <%= link_to("取消",group_path(@group),class:"btn btn-default") %>
    
	
	<%end %>
	